//Program_70
/* Write a progam with the following specifications:
 * Class name: Latin
 * Data Members: String name
 * Member funtions:
 *  Latin()- default construct to initialise the string
 *  void input(String n) to accept name and convert and print the name in Pig Latin*
 *  *Pig Latin is an encrypted word in english which is generated by the following alterations:
 *  
 *  Input-  LONDON   / AMAZON   / BANGALORE
 *  Output- ONDONLAY / AMAZONAY / ANGALOREBAY
 */
//7.8.23
//Suday Dutta
//Greenwood High
import java.util.Scanner;
class Latin
{
    String name;
    Latin()
    {
        name = "";
    }
    void input(String n)
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter your name below:");
        n = sc.next();
        n = n.toUpperCase();
        int i;
        for(i = 0; i < n.length(); i++)
        {
            char ch = n.charAt(i);
            if(ch == 'a' || ch == 'e' || ch == 'i' || ch == 'o' || ch == 'u')
            {
                break;
            }
        }
        String pig_latin = n.substring(i); 
        pig_latin += n.substring(0, i); 
        pig_latin +="AY";
        System.out.println(n + " in Pig Latin is: "+pig_latin);
    }
    public static void main()
    {
         Latin pig_latin = new Latin();
         String nian ="";
         pig_latin.input(nian);
    }
}