//Program_70
/* Write a progam with the following specifications:
 * Class name: Latin
 * Data Members: String name
 * Member funtions:
 *  Latin()- default construct to initialise the string
 *  void input(String n) to accept name and convert and print the name in Pig Latin*
 *  *Pig Latin is an encrypted word in english which is generated by the following alterations:
 *  
 *  Input-  LONDON   / AMAZON   / BANGALORE
 *  Output- ONDONLAY / AMAZONAY / ANGALOREBAY
 */
//7.8.23
//Suday Dutta
//Greenwood High
import java.util.Scanner;
class Latin
{
    String name;
    Latin()
    {
        name = "";
    }

    void input(String n)
    {
        name = n + "AY";
        int i;
        for(i = 0; i < n.length(); i++)
        {
            char ch = name.charAt(i);
            if(ch == 'A' || ch == 'E' || ch == 'I' || ch == 'O' || ch == 'U')
            {
                String pig_latin = name.substring(i) + name.substring(0, i) + "AY";
                 
                System.out.println(name + " in Pig Latin is: "+pig_latin);
                break;
            }
        }
    }

    public static void main()
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter your name below:");
        String n = sc.next();
        n = n.toUpperCase();
        Latin pig_latin = new Latin();
        pig_latin.input(n);
    }
}